# -*- coding: utf-8 -*-
"""4 march py.pws

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WE5BQk1G-K1rC4EJRA-vmogIwt7e0owd
"""

# Q1
import plotly.graph_objects as go
import seaborn as sns
titanic = sns.load_dataset('titanic')

fig = go.Figure()
fig.add_trace(go.Scatter(x = titanic.age, y = titanic.fare , mode = 'markers'))

# Q2
import plotly.graph_objects as go
import seaborn as sns
import plotly.express as px
tips = sns.load_dataset('tips')

fig = px.box(tips, x = "sex", y="total_bill", points="all")
fig.update_traces(quartilemethod="inclusive")
 
fig.show()

# Q3
import plotly.graph_objs as go
import seaborn as sns
import plotly.express as px
tips = sns.load_dataset('tips')

fig = px.histogram(tips, x="sex" ,y="total_bill", pattern_shape= "smoker" , color= "day")
fig.show()

# Q4
import plotly.graph_objects as go
import seaborn as sns
import plotly.express as px

iris = sns.load_dataset('iris')

fig = px.scatter_matrix(iris,
    dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],
    color="species")
fig.show()

# Q5
#Distplot:-
'''The distplot figure factory displays a combination of statistical representations of numerical data, such as histogram, 
kernel density estimation or normal curve, and rug plot.'''
#example
import plotly.graph_objects as go
import plotly.express as px

tips = px.data.tips()
fig = px.histogram(tips, x="total_bill", y="tip", color="sex", marginal="rug",
                   hover_data=df.columns)
fig.show()

